### ISSUE TITLE
2021 - API 2.0 updates

### ISSUE THREAD

**Issue by stonko1994** [b3ll/F1TV#2]
### Master Issue for API v2.0 support

After the **Bahrain GP 2021**, the backend for `f1tv` changed so that it was no longer possible to use the current App for live streams.

_This issue tracks the needed steps to support the features as before the API updates._

**Tasks:**

- [x] Update to new authorization (#3)
- [x] Get active Race Weekend (#3)
- [x] Play live streams (#3)
  - [ ] Play Player Onboards
  - [ ] Play additional streams (driver tracker / time sheet)
  - [ ] FIlter by class (F1, F2 etc)
- [ ] Play content from current season (2021)
- [ ] Play content from previous seasons
